[IV-21-22] Objetivo 2
migueorg/SearchCulture pull request #10
Opened 2021-10-20 12:21 UTC by arguellesm

### Descripción de los cambios

Se han añadido las clases `Usuario` y `Pregunta`, se ha creado un módulo (`to_csv`) que permite exportar datos de usuarios a CSV, y se ha creado un _frontend_ sencillo para mostrar las preguntas y recoger sus respuestas.

Con esto debería cerrarse #3 (_close_ #3), además de las issues individuales mencionadas en los _commits_.

### Ejemplo de uso

El siguiente código genera el formulario que se muestra en la imagen y descarga un archivo CSV con los datos de los usuarios de prueba.

![form](https://user-images.githubusercontent.com/11518301/138090719-c439dd14-3057-40b1-8fff-e2007eb98802.png)

##### Ejemplo de CSV
```csv
tipo,alta,region,intereses
1,2021-10-20 11:10:39.214698,ES,"[['Respuesta A', 'Respuesta B', 'Respuesta A']]"
1,2021-10-20 11:10:39.214712,IT,"[['Respuesta A', 'Respuesta B', 'Respuesta A']]"
2,2021-10-20 11:10:39.214715,PT,"[['Respuesta A', 'Respuesta B', 'Respuesta A']]"
```
##### Ejemplo de aplicación
```python
from flask import Flask, request, render_template, send_from_directory
from datetime import datetime
from model import Usuario, Pregunta, to_csv

app = Flask(__name__, static_folder='view/css', template_folder='view/html')

@app.route('/', methods=["GET", "POST"])
def preguntas():
    # crear preguntas
    p = [
        Pregunta('radio','Enunciado de la primera pregunta.',
            ['Respuesta A','Respuesta B','Respuesta C']),
        Pregunta('radio','Enunciado de la segunda pregunta.',
            ['Respuesta A','Respuesta B']),
        Pregunta('checkbox','Enunciado de la tercera pregunta.',
            ['Respuesta A','Respuesta B','Respuesta C'])
    ]

    action = '/csv'
    
    # generar plantilla con las preguntas
    return render_template('preguntas.html', preguntas = p,
            action = action)

@app.route('/csv', methods=["GET", "POST"])
def get_csv():
    # guardar intereses
    respuestas = request.form.to_dict()
    intereses = list(respuestas.values())

    # crear usuarios
    u = [
        Usuario(1,datetime.now(),'ES',intereses),
        Usuario(1,datetime.now(),'IT',intereses),
        Usuario(2,datetime.now(),'PT',intereses)
    ]

    # convertir a csv
    filename='users.csv'
    to_csv(u,filename)

    # devolver dichero para descarga
    return send_from_directory(directory='.', path=filename, as_attachment=True)
```
_Nota_. El código no es parte de SearchCulture, lo incluyo para dar un ejemplo del funcionamiento.

2021-10-20 12:22 UTC, arguellesm commented
@migueorg listo para revisión!

2021-10-31 12:51 UTC, arguellesm commented
He incluido el conteo de palabras como comentaste. En vez de usar `map()` lo he hecho con un objeto [`Counter`](https://docs.python.org/3/library/collections.html#collections.Counter), que creo que es más directo.

2021-11-03 11:59 UTC, migueorg commented
Desconocía la existencia de Counter, me parece muy acertado! Buen trabajo @arguellesm!!

Por mi parte, listo para revisión @JJ

2021-11-06 11:55 UTC, JJ requested changes
Se ha hecho un trabajo inicial adecuado, pero en general, [conviene que se compruebe lo hecho contra esta lista de comprobación](http://jj.github.io/IV/documentos/proyecto/2.Entidad#lista-de-comprobaci%C3%B3n).
Ya he hecho comentarios anteriormente que no se han escuchado, como por ejemplo el hecho de que los issues reflejen un problema. Commits como d5ff6a2 no hacen referencia a ningún issue, y no se sabe por qué se hace. Aunque @arguellesm en general ha seguido la mayoría de las indicaciones de @migueorg, convendría que, una por una, contestara a todas las objeciones que he puesto aquí para poder cumplir este objetivo.

2021-11-06 11:55 UTC, JJ commented on src/usuario.py
> +    region : str
No hay ninguna referencia a la región en la HU.

2021-11-06 11:55 UTC, JJ commented on src/usuario.py
> +    tipo : int
No hay ninguna referencia al tipo, ni ninguna relación aparente con la lógica de negocio. En todo caso, debería ser probablemente un enum (y debería tener un issue para definirlo)

2021-11-06 11:55 UTC, JJ commented on src/usuario.py
> +        self.conteo = Counter(palabras)
No hay ninguna indicación de qué problema resuelve esta estructura de datos.

2021-11-19 13:28 UTC, migueorg commented
Tras la reestructuración de la lógica de negocio 5323b080a4d7c5d1d8b23877b79d8c76d0415ffc cambia un poco el planteamiento del proyecto... Mis disculpas @arguellesm por esta inestabilidad. Tal y como está enfocado actualmente el PR y el proyecto, los cambios que sugiero son los siguientes:
- Eliminar el atributo tipo de la clase Usuario.
- Añadir un atributo a la clase pregunta para usarse como identificador de cada pregunta.
- Añadir un atributo a la clase usuario para usarse como identificador de cada usuario.
- Crear una clase respuesta con atributos id_usuario e id_pregunta junto con un string con la respuesta en cuestión.

Otras modificaciones que afectan al PR pero que no implican desarrollo alguno, ambos apreciables en 2222239cb153feb10b577c0c75e4406267f8952a :
- Ahora si es de interés la región del usuario.
- También pasa a ser de interés la fecha en la que se responde la pregunta.

Para acabar, también he borrado el issue referente al frontend pues fue descartado inicialmente.

Los cambios pueden verse reflejados en master o en la rama Objetivo-1.5 que he creado específicamente para esto.

2021-11-22 10:12 UTC, arguellesm commented on src/usuario.py
> +    region : str
La región es uno de los atributos especificados en la HU [#3](https://github.com/migueorg/SearchCulture/issues/3#:~:text=Regi%C3%B3n/Ubicaci%C3%B3n%20del%20usuario), por eso se incluye.

2021-11-22 10:14 UTC, arguellesm commented on src/usuario.py
> +    tipo : int
Como ha dicho @migueorg, con https://github.com/migueorg/SearchCulture/commit/5323b080a4d7c5d1d8b23877b79d8c76d0415ffc se reestructura la lógica de negocio y desaparece el **tipo**, que se ha eliminado de la clase usuario en https://github.com/migueorg/SearchCulture/pull/10/commits/68bb20cf532ea153f157db2f3f69b0e18cbf7fc6.

2021-11-22 10:22 UTC, arguellesm commented on src/usuario.py
> +        self.conteo = Counter(palabras)
Como explica @migueorg en https://github.com/migueorg/SearchCulture/commit/5323b080a4d7c5d1d8b23877b79d8c76d0415ffcm:
-  La **región** se usa para conocer las demandas de los usuarios en función de dónde vivan. Esta información se traslada a las productoras, que podrían usarla para decidir en qué sitios se estrenan películas poco comerciales que requieran de una audiencia concreta. 
- Los **intereses** y el **conteo de palabras** se emplean para hacer recomendaciones ajustadas a cada usuario mediante [algoritmos de clasificación](https://en.wikipedia.org/wiki/Statistical_classification).

2021-11-22 10:27 UTC, arguellesm commented
Listo para revisión @migueorg!

Además de los cambios que se ven en los commits, he editado https://github.com/migueorg/SearchCulture/issues/11 para que refleje los cambios que ha sufrido la clase Usuario.

2021-11-23 14:57 UTC, migueorg commented
Por mi parte está correcto. Buen trabajo!!
Listo para revisión @JJ 👍

2021-11-28 10:59 UTC, JJ approved these changes
:+1: y perdón por el retraso.

2021-12-02 10:42 UTC, merged