[IV-21-22] Objetivo 4
migueorg/SearchCulture pull request #25
Opened 2022-01-06 22:04 UTC by migueorg

En este PR:

* [x]  ¿Hay un camino claro que permita ir desde el código hasta la historia de
   usuario que desarrolla, pasando por el mensaje de commit y el issue
   correspondiente?
* [x]  ¿Se ha intentado cubrir con tests una parte de la lógica de negocio que se
   esté desarrollando?
* [x]  ¿Hay un producto mínimamente viable que describa lo que se va a entregar en
   este objetivo?
* [x]  ¿En este producto mínimamente viable se han priorizado unas clases,
   módulos o paquetes más fundamentales frente a otros, movidos a otro
   PMV/Hito?
* [x]  ¿Se han documentado las elecciones de biblioteca de aserciones y del
   de *test runner*?
* [x] ¿Te has asegurado que lo que mencionas como biblioteca de aserciones y
test runners lo son realmente y tienen la misma funcionalidad? ¿O estás poniendo
`unittest` como *test runner* y `pytest` como biblioteca de aserciones?
* [x] ¿Esa documentación incluye criterios de aceptación y también criterios de
búsqueda para las diferentes opciones?
* [x]  ¿Se han seguido los principios F.I.R.S.T. en la creación del test y
   se ha documentado cómo se ha hecho?
* [x]  ¿Se describe claramente en el PMV los tests que hay que pasar para que se
   considere viable?

Se ha realizado lo marcado en las casillas. Pero adicionalmente en rasgos generales:
- Se han creado los issues #21 , #22  y #23 sobre los que se trabaja en este PR. Los cuales serán cerrados una vez se acepte este PR.
- Se ha reorganizado y actualizado el [PMV sobre el que se trabaja](https://github.com/migueorg/SearchCulture/milestone/7)
- Se ha elegido un marco de ejecución y una biblioteca de aserciones para implementar los test unitarios. Dicha elección se ha reflejado en el archivo docs/test.md 8170390262b2202b82ca4d5a76151e11fec13b78
- Se ha documentado la verificación de los principios F.I.R.S.T. 09e05833e130af1c6ec1a42ac0cf4af03123f973
- Se han desarrollado los test unitarios b3579996ee9ab1dc70d23c3426fcf8ab25b7c916 18e5f97b49c50c7c5227d56f8166015832c8fa24 eb97806856d1c92e807799b6d79ed79c719e4e1b
- Se han actualizado las dependencias del proyecto e2c0d46c31098c3f4b278693b1b0cce17f1b1ad0
- Se han actualizado las tareas del task runner a4d8f6a936ba371686fbd9c31780e59aa521875d
- Se han añadido nuevos detalles en el README dd90523344586faf7caef05546c9e6e4440cde5e

2022-01-06 22:07 UTC, JJ commented
⛹ Revisores → @gomares @aleveji @Balrrach

2022-01-07 14:34 UTC, gomares reviewed
En general muy buen trabajo 💯. La documentación me ha sorprendido gratamente aunque tengo algunas propuestas para que te quede un trabajo aún mejor.

2022-01-07 19:56 UTC, migueorg commented
> En general muy buen trabajo 💯. La documentación me ha sorprendido gratamente aunque tengo algunas propuestas para que te quede un trabajo aún mejor.

Muchas gracias @gomares ! 
Por mi parte encantado de escuchar esas propuestas! (o no sé si las has escrito y no me salen :sweat_smile:)

2022-01-08 23:11 UTC, morevi commented
Tambien lo veo genial 👌🏼, se vé que has investigado las posibilidades y la justificación de las herramientas parece correcta. Si tuviese que señalar algo, habría hecho algo de enfasis en alguna funcionalidad, de los frameworks, que te interese usar en los tests (fixtures, setup, teardown, por ejemplo), aparte de las que ya has señalado.

2022-01-09 14:10 UTC, arguellesm reviewed
Lo veo muy bien! La documentación está muy clara y creo que haces buen análisis de las alternativas que tienes teniendo en cuenta tus prioridades, solo tengo un comentario sobre los tests.

2022-01-09 14:10 UTC, arguellesm commented on test/test_respuesta.py
> +#Comprueba que la creación de los objetos Respuesta se hacen correctamente
Como el PEP 8 recomienda limitar los comentarios _inline_, usaría _docstrings_ como has hecho en `Respuesta`, o cambiaría los nombres de las funciones de test para que fuesen más descriptivos y no necesitasen documentación.

2022-01-19 17:16 UTC, JJ requested changes
El problema principal, aparte de la confusión con lo que son o no una biblioteca de aserciones, es que no testeas nada de la lógica de negocio, lo que era esencial en este hito. Por lo demás, has seguido bastante estrictamente las buenas prácticas.

2022-01-19 17:16 UTC, JJ commented on docs/test.md
> +Tras el análisis de las alternativas encontradas, las herramientas que cumplen más criterios de los que busco son Unittest y Pytest. Ambos cumplen el mismo número de requisitos, pero no los mismos. P
Pero si has puesto unittest como test runner...

2022-01-19 17:16 UTC, JJ commented on docs/test.md
> +- [unittest](https://github.com/python/cpython/tree/main/Lib/unittest)
Vamos a ver. O es un test runner o es una biblioteca de aserciones.

2022-01-19 17:16 UTC, JJ commented on docs/test.md
> +  - [ ] No cumple el requisito pues tiene una sintaxis bastante arcaica, obsoleta, repetitiva y poco natural, haciendo que sea liosa.
Pero si tiene la sintaxis de Python...

2022-01-30 14:06 UTC, migueorg commented
> Tambien lo veo genial 👌🏼, se vé que has investigado las posibilidades y la justificación de las herramientas parece correcta. Si tuviese que señalar algo, habría hecho algo de enfasis en alguna funcionalidad, de los frameworks, que te interese usar en los tests (fixtures, setup, teardown, por ejemplo), aparte de las características que ya has señalado.

Muchas gracias por tu revisión!!, me ha parecido buena idea por lo que he añadido como criterio extra que tenga posibilidad de usar fixtures, aunque actualmente no les dé uso, pero con vista a futuro poder usarlo, por lo que he creado el issue #26 y se ha cerrado con el commit 1b194e7

2022-01-30 14:11 UTC, migueorg commented on test/test_respuesta.py
> +#Comprueba que la creación de los objetos Respuesta se hacen correctamente
Muchas gracias por tu revisión, un gusto verte de nuevo por aquí! Efectivamente, se me pasó usar los principios PEP 8 en esa clase, para solucionarlo he creado el issue #27 y se ha cerrado con el commit 2c8b8ca optando por usar _docstrings_ al igual que en `Respuesta`.

2022-01-30 14:26 UTC, migueorg commented on docs/test.md
> +- [unittest](https://github.com/python/cpython/tree/main/Lib/unittest)
Efectivamente, no es un test runner, tuve confusión y sumado a que en la documentación oficial vi ejemplos de salida del propio fichero ejecutados (sin test runner) con el fin de probar el script, pensé que esa era su salida.
 
[Fuente](https://docs.python.org/3/library/unittest.html#basic-example)

<img width="220" alt="imagen" src="https://user-images.githubusercontent.com/48918518/151703504-b88d1e14-3480-4c93-864e-1cc700fd87b8.png">


Pero ya ha sido eliminado y me he informado correctamente al respecto, viendo que efectivamente estaba equivocado y se trata de una librería de aserciones.

2022-01-30 14:27 UTC, migueorg commented on docs/test.md
> +Tras el análisis de las alternativas encontradas, las herramientas que cumplen más criterios de los que busco son Unittest y Pytest. Ambos cumplen el mismo número de requisitos, pero no los mismos. P
Corregido y eliminado en 7f54d35 👍

2022-01-30 14:31 UTC, migueorg commented on docs/test.md
> +- [unittest](https://github.com/python/cpython/tree/main/Lib/unittest)
Definitivamente, es una biblioteca de aserciones, no lo entendí del todo bien en la anterior revisión. He añadido una explicación de lo sucedido al respecto [aquí](https://github.com/migueorg/SearchCulture/blob/38d87903f5eb707f4e84898dae427fa7db0099a9/docs/test.md#aclaraci%C3%B3n-sucedido-con-unittest) con el commit 38d8790

2022-01-30 14:34 UTC, migueorg commented on docs/test.md
> +  - [ ] No cumple el requisito pues tiene una sintaxis bastante arcaica, obsoleta, repetitiva y poco natural, haciendo que sea liosa.
A pesar de que la sintaxis de Python es buena y tiene fama de fácil, al comparar la sintaxis de dicha biblioteca de aserciones, con otras que tratan de tener una sintaxis lo más humana posible, hace que en comparación no se vea tan bien. Igualmente, también he aclarado un poco lo que quería decir en el archivo.

2022-01-30 14:54 UTC, migueorg commented
@JJ aún no está listo para revisión porque tengo una duda al respecto:

He corregido casi todos los problemas que han sido destacados, pero con el tema de no testar la lógica de negocio hay algo que me genera dudas. La lógica de negocio que redacté en el apartado de [¿Cómo funciona?](https://github.com/migueorg/SearchCulture/blob/4f6617c67861b6ec0b0f6380bad0e2271d9d21d0/docs/contexto.md#c%C3%B3mo-funciona) en docs/contexto.md menciona en la línea 49 que se extraerá un conteo de las palabras que componen una respuesta para ponderarlas según que palabra sea y el número de veces que se haya dicho, y eso es lo que he implementado y testeado, es decir, la extracción y paso de respuesta a palabras ya contadas en forma de diccionario. Lo cual considero que es la primera parte y mínima de la lógica de negocio.

Pero el PMV al que estaba ligado este PR no mencionaba eso, por lo que he entendido que el no testear la lógica de negocio es referente a la parte de la lógica que implementa dicho PMV, por lo que lo he reestructurado y he movido cierta parte de funcionalidad a otro PMV para que este concuerde con la parte de la lógica de negocio que estoy testeando. 

¿Era eso lo que hacía que no estuviese testeando la lógica de negocio? ¿O debo de expandir la funcionalidad aún más para testear otras cosas?

Una vez aclarado esta duda, lo marcaré como listo para revisión, pues tengo cierto temor a no haber entendido correctamente la revisión sobre la lógica de negocio, es por eso mi pregunta.

2022-01-30 16:04 UTC, JJ commented
> @JJ aún no está listo para revisión porque tengo una duda al respecto:
> 
> He corregido casi todos los problemas que han sido destacados, pero con el tema de no testar la lógica de negocio hay algo que me genera dudas. La lógica de negocio que redacté en el apartado de [¿Cómo funciona?](https://github.com/migueorg/SearchCulture/blob/4f6617c67861b6ec0b0f6380bad0e2271d9d21d0/docs/contexto.md#c%C3%B3mo-funciona) en docs/contexto.md menciona en la línea 49 que se extraerá un conteo de las palabras que componen una respuesta para ponderarlas según que palabra sea y el número de veces que se haya dicho, y eso es lo que he implementado y testeado, es decir, la extracción y paso de respuesta a palabras ya contadas en forma de diccionario. Lo cual considero que es la primera parte y mínima de la lógica de negocio.
> 
> Pero el PMV al que estaba ligado este PR no mencionaba eso, por lo que he entendido que el no testear la lógica de negocio es referente a la parte de la lógica que implementa dicho PMV, por lo que lo he reestructurado y he movido cierta parte de funcionalidad a otro PMV para que este concuerde con la parte de la lógica de negocio que estoy testeando.
> 
> ¿Era eso lo que hacía que no estuviese testeando la lógica de negocio? ¿O debo de expandir la funcionalidad aún más para testear otras cosas?
> 
> Una vez aclarado esta duda, lo marcaré como listo para revisión, pues tengo cierto temor a no haber entendido correctamente la revisión sobre la lógica de negocio, es por eso mi pregunta.

Se trata de que se hagan tests no triviales sobre funciones no triviales. Esa es la idea. A partir de ahí, si es un procesamiento no trivial relacionado con la lógica de negocio, es lo que se busca.

2022-01-30 22:07 UTC, migueorg commented
> > @JJ aún no está listo para revisión porque tengo una duda al respecto:
> > He corregido casi todos los problemas que han sido destacados, pero con el tema de no testar la lógica de negocio hay algo que me genera dudas. La lógica de negocio que redacté en el apartado de [¿Cómo funciona?](https://github.com/migueorg/SearchCulture/blob/4f6617c67861b6ec0b0f6380bad0e2271d9d21d0/docs/contexto.md#c%C3%B3mo-funciona) en docs/contexto.md menciona en la línea 49 que se extraerá un conteo de las palabras que componen una respuesta para ponderarlas según que palabra sea y el número de veces que se haya dicho, y eso es lo que he implementado y testeado, es decir, la extracción y paso de respuesta a palabras ya contadas en forma de diccionario. Lo cual considero que es la primera parte y mínima de la lógica de negocio.
> > Pero el PMV al que estaba ligado este PR no mencionaba eso, por lo que he entendido que el no testear la lógica de negocio es referente a la parte de la lógica que implementa dicho PMV, por lo que lo he reestructurado y he movido cierta parte de funcionalidad a otro PMV para que este concuerde con la parte de la lógica de negocio que estoy testeando.
> > ¿Era eso lo que hacía que no estuviese testeando la lógica de negocio? ¿O debo de expandir la funcionalidad aún más para testear otras cosas?
> > Una vez aclarado esta duda, lo marcaré como listo para revisión, pues tengo cierto temor a no haber entendido correctamente la revisión sobre la lógica de negocio, es por eso mi pregunta.
> 
> Se trata de que se hagan tests no triviales sobre funciones no triviales. Esa es la idea. A partir de ahí, si es un procesamiento no trivial relacionado con la lógica de negocio, es lo que se busca.

Entiendo entonces que funciones triviales serían getter y setters de una clase, pero que las funciones como descomposición de palabras, conteo y almacenado de los resultados en un diccionario y cálculo de la palabra más repetida no serían funciones triviales, y que al ser test de funciones que realizan lo que describe la lógica de negocio que implementa el PMV asociado, tampoco serían triviales, ¿no?

2022-01-31 17:54 UTC, JJ commented
⛹ Revisores → @Asmilex @modejota @jesusmarzor

2022-01-31 18:09 UTC, LuisSS20 commented
Como te han dicho los demás compañeros, toda la documentación así como la buenas prácticas, según mi parecer lo has hecho genial 👍 . 
Sin embargo, no veo del todo la lógica de negocio. He visto que tu proyecto trata sobre recomendar películas, series, libros... en base a respuestas. Según esto, para poder ayudarte un poco y cubrir parte de la lógica de negocio, puedo recomendarte lo siguiente:

- Crear una estructura de datos que almacene, por ejemplo, una película y unas palabras clave asociadas a esta para poder recomendarla -> ('Star Wars: Episodio IV - Una nueva esperanza', 'Ciencia ficción, Espacio, Fantasía, Acción')
- Crear una estructura que almacene géneros ( o las palabras clave asociadas a lo que se recomendará)  y los relacione con otras palabras del lenguaje. Por ejemplo, Acción -> 'Peleas, Disparos, Combate'. Y así, cuando le preguntes al usuario y este responda con alguna de estas palabras (Peleas, Disparos, Combate...), el algoritmo sea capaz de recomendar películas relacionadas a lo contestado.

Espero que con esto puedas guiarte y cubrir parte de la lógica de negocio. Si necesitas alguna aclaración pregúntame sin problema.

2022-02-01 15:38 UTC, JJ commented
> > > @JJ aún no está listo para revisión porque tengo una duda al respecto:
> > > He corregido casi todos los problemas que han sido destacados, pero con el tema de no testar la lógica de negocio hay algo que me genera dudas. La lógica de negocio que redacté en el apartado de [¿Cómo funciona?](https://github.com/migueorg/SearchCulture/blob/4f6617c67861b6ec0b0f6380bad0e2271d9d21d0/docs/contexto.md#c%C3%B3mo-funciona) en docs/contexto.md menciona en la línea 49 que se extraerá un conteo de las palabras que componen una respuesta para ponderarlas según que palabra sea y el número de veces que se haya dicho, y eso es lo que he implementado y testeado, es decir, la extracción y paso de respuesta a palabras ya contadas en forma de diccionario. Lo cual considero que es la primera parte y mínima de la lógica de negocio.
> > > Pero el PMV al que estaba ligado este PR no mencionaba eso, por lo que he entendido que el no testear la lógica de negocio es referente a la parte de la lógica que implementa dicho PMV, por lo que lo he reestructurado y he movido cierta parte de funcionalidad a otro PMV para que este concuerde con la parte de la lógica de negocio que estoy testeando.
> > > ¿Era eso lo que hacía que no estuviese testeando la lógica de negocio? ¿O debo de expandir la funcionalidad aún más para testear otras cosas?
> > > Una vez aclarado esta duda, lo marcaré como listo para revisión, pues tengo cierto temor a no haber entendido correctamente la revisión sobre la lógica de negocio, es por eso mi pregunta.
> > 
> > 
> > Se trata de que se hagan tests no triviales sobre funciones no triviales. Esa es la idea. A partir de ahí, si es un procesamiento no trivial relacionado con la lógica de negocio, es lo que se busca.
> 
> Entiendo entonces que funciones triviales serían getter y setters de una clase, pero que las funciones como descomposición de palabras, conteo y almacenado de los resultados en un diccionario y cálculo de la palabra más repetida no serían funciones triviales, y que al ser test de funciones que realizan lo que describe la lógica de negocio que implementa el PMV asociado, tampoco serían triviales, ¿no?

Los getters y setters, en general, tienes que preguntarte si son necesarios o no. Lo más probable es que no. En todo caso, no te puedo decir si son triviales o no hasta que no los corrija (o alguno de los revisores)

2022-02-01 21:10 UTC, LuisSS20 commented
> > Como te han dicho los demás compañeros, toda la documentación así como la buenas prácticas, según mi parecer lo has hecho genial 👍 . Sin embargo, no veo del todo la lógica de negocio. He visto que tu proyecto trata sobre recomendar películas, series, libros... en base a respuestas. Según esto, para poder ayudarte un poco y cubrir parte de la lógica de negocio, puedo recomendarte lo siguiente:
> > ```
> > * Crear una estructura de datos que almacene, por ejemplo, una película y unas palabras clave asociadas a esta para poder recomendarla -> ('Star Wars: Episodio IV - Una nueva esperanza', 'Ciencia ficción, Espacio, Fantasía, Acción')
> > 
> > * Crear una estructura que almacene géneros ( o las palabras clave asociadas a lo que se recomendará)  y los relacione con otras palabras del lenguaje. Por ejemplo, Acción -> 'Peleas, Disparos, Combate'. Y así, cuando le preguntes al usuario y este responda con alguna de estas palabras (Peleas, Disparos, Combate...), el algoritmo sea capaz de recomendar películas relacionadas a lo contestado.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Espero que con esto puedas guiarte y cubrir parte de la lógica de negocio. Si necesitas alguna aclaración pregúntame sin problema.
> 
> Muchas gracias por tu revisión y por las ideas! Tras tus comentarios he decidido extender la implementación de la lógica de negocio, para ello he creado el issue #29 sobre el que he ido trabajando.
> 
> Un resumen de lo que se ha hecho basándome en tus comentarios:
> 
> * Ahora el proyecto además de analizar las respuestas como hacía en la revisión anterior, también recibe las preguntas junto con su respectivo diccionario en el que contiene el significado de los géneros según las posibles palabras contenidas en las respuestas, y para enlazarlas se ha creado una clase nexo que recibe una pregunta y una respuesta, y las analiza buscando cada una de las palabras del diccionario de pregunta en la respuesta, si las encuentra se suma el número de veces que haya aparecido al género correspondiente en un diccionario de la clase nexo, para así obtener una valoración sobre el género preferido según esa respuesta. Ya que el proceso de buscar una película según este cálculo y procesado de género es parte de otro PMV ajeno a este.
> * Además, se ha añadido test para todo lo mencionado nuevo.
> * También se ha actualizado el PMV actual añadiendo los test que son necesarios pasar para que se considere viable.
> 
> Quedo a la espera de tu opinión tras las modificaciones y si tienes alguna objeción al respecto o lo ves ya listo para revisión final. 😊

Con lo que has añadido, veo algo más de lógica de negocio. A mi parecer esta aceptable para este objetivo.
Como última sugerencia eliminaría algunos getters y setters que no usas, por ejemplo el id del cliente.

2022-02-02 18:37 UTC, migueorg commented
Tras haber atendido y solucionado todas las revisiones, y con ellas haber extendido también la lógica de negocio, por mi parte listo para revisión @JJ 👍

2022-02-08 16:33 UTC, JJ approved these changes
:+1: No es perfecto, pero es adecuado. Si cambias lo indicado para el siguiente objetivo, mejor.

2022-02-08 16:33 UTC, JJ commented on src/pregunta.py
> +        self.ponderaciones = ponderaciones
No sé por qué necesitas un id aquí, pero no es de este objetivo.

2022-02-08 16:33 UTC, JJ commented on src/pregunta.py
> +    def get_ponderaciones(self):
¿Quién va a llamar a esto?

2022-02-08 16:33 UTC, JJ commented on src/respuesta.py
> +    def almacena_palabras(self):
¿Vas a reescribir el diccionario cada vez?

2022-02-08 16:33 UTC, JJ commented on task.yaml
> +      cmd: pip3 install -U pytest==6.2.5
En 2021 debes usar poetry como gestor de dependencias. Tampoco es de este objetivo, pero bueno...

2022-02-09 00:45 UTC, migueorg commented
> 👍 No es perfecto, pero es adecuado. Si cambias lo indicado para el siguiente objetivo, mejor.

Gracias. Tomo nota en forma de issue de los cambios a realizar y los arreglaré en el PR del Objetivo 5 para intentar evitar así conflictos a la hora de hacer el merge.

2022-02-09 00:51 UTC, merged